

export const PortfolioText = {
    web_text_1: "With two years of web development experience, I've built a solid foundation in creating dynamic and responsive web applications. I started with HTML and CSS, which gave me the basics of web design. Then, I moved on to JavaScript and Django, where I learned how the frontend and backend connect. Getting into React.js was a game-changer for me. It helped me build complex and interactive user interfaces, and I picked up important skills like state management, data fetching, authentication, and working with APIs. Along the way, I’ve continually added new tools and technologies to my toolkit to keep up with the latest trends.",
    web_text_2: "Getting into React.js was a game-changer for me. It helped me build complex and interactive user interfaces, and I picked up important skills like state management, data fetching, authentication, and working with APIs. Along the way, I’ve continually added new tools and technologies to my toolkit to keep up with the latest trends.",
    web_text_3: "I’m always learning and excited to explore new technologies and methods to improve my skills. I enjoy environments where I can challenge myself and grow.",
    web_text_end: "Looking ahead, I’m aiming to become a software engineer. I want to dive into React Native to expand into mobile app development and learn Python for its versatility. Plus, I’m keen on getting a deeper understanding of advanced database concepts to design better and more efficient data solutions.",

    pm_text_1: "With a bachelor's degree in project management from Purdue Global University and an ITIL Foundation Certificate, I've built a comprehensive understanding of managing projects from start to finish. My journey began with the basics of project planning and organization, where I learned how to break down complex projects into manageable tasks. This foundation helped me develop strong skills in creating timelines, setting milestones, and ensuring projects stay on track.",
    pm_text_2: "My ITIL Foundation Certificate has been particularly valuable in IT project management, aligning well with my web development expertise. It has equipped me with a solid understanding of IT service management best practices, which I apply to ensure that IT projects deliver value and meet business objectives.",
    pm_text_3: "Looking ahead, I'm excited to deepen my knowledge in agile methodologies and explore certifications like PMP (Project Management Professional) to further enhance my expertise. I’m also interested in learning more about how technology can streamline project management processes and improve efficiency.",

    marketing_1: "Even though I majored in Project Management at university, I found myself getting really interested in marketing after my first marketing class. It was so fascinating that I decided to switch five of my elective courses to marketing-related ones. After graduating, I didn't stop there – I took some extra courses and got certified in a couple of cool areas:",
    marketing_2: "I took a course—Viral Marketing and How to Craft Contagious Content from The University of Pennsylvania taught by Jonah Berger. And the following are the concepts that interest me the most:",
    marketing_3: "Viral Marketing and crafting contagious content revolves around understanding why some ideas, products, or behaviors catch on and spread while others don't. According to Berger, the key to creating viral content lies in six principles, summarized by the acronym STEPPS:",
    marketing_4: "These principles guide the creation of content that is inherently shareable and can go viral. By leveraging social influence, psychological triggers, and emotional responses, marketers can craft content that spreads naturally and effectively.",
    concept_1: "People share things that make them look good or enhance their status. Crafting content that makes sharers feel special, knowledgeable, or in-the-know can increase the likelihood of sharing.",
    concept_2: "Ideas that are top of mind are more likely to be talked about. Linking your product or idea to common triggers in the environment can make people think of it more often.",
    concept_3: "Content that evokes strong emotions is more likely to be shared. High arousal emotions like awe, excitement, amusement, or anger motivate people to share more than low arousal emotions like contentment or sadness.",
    concept_4: "Making behavior more public encourages imitation. If people can see others using a product or engaging with content, they are more likely to do the same. Making the private public can help.",
    concept_5: "People share content that has practical value. Useful information, tips, and advice are more likely to be passed along.",
    concept_6: "People don’t just share information; they share stories. Wrapping your product or idea in a compelling narrative helps ensure that the message is not only shared but remembered.",

    art_1: "Before diving into the world of web development, project management, and marketing, I was (and still am) an artist at heart. I've been an artist my whole life, starting off as a graphic designer and even doing art commissions, creating character concepts for people online. Art is my passion, and it’s one of the reasons I enjoy web development so much – it’s just another canvas for creativity.",
    art_2: "I'm a versatile creative who's passionate about blending art and technology. From web development to project management, marketing, and, most importantly, art – I do it all! But let's dive into what makes me tick.",
    art_3: "Graphic design was my first love. I started out designing prints, logos, and all sorts of visual goodies. Adobe Photoshop is my favorite tool. Whether it's creating a brand identity or some marketing materials, I've got it covered.",
    art_4: "Digital painting is where I feel the most relaxed and have the most fun. Using Adobe Photoshop, I find myself drawn to character designs, where I can bring unique personalities to life through art. This process is not just a task but a joy, allowing me to explore different styles and techniques. It's my happy place, where creativity flows freely.",
    art_5: "Video editing is all about telling a story through visuals. I've tried many different software such as Sony Vegas, Adobe Premiere Pro, and Adobe After Effects. However, nowadays, I only use Wondershare Filmora and CapCut for mobile content.",
}