export const aboutText = {
    greeting: "Hello There,",
    // intro: "I'm Jakkrit Turner, and I'm delighted to welcome you to my portfolio. As a dedicated professional with a diverse skill set, I specialize in project management and ITIL, where I excel at orchestrating successful projects and implementing best practices for IT services.",
    intro: "I'm Jakkrit Turner, and I'm delighted to welcome you to my world and get to know me better. As a dedicated professional with a diverse skill set, I specialize in web development, project management, marketing, and art. But there's so much more to my story.",
    intro2: "Way before I got into web development, project management, and marketing, I was all about art. I started as a graphic designer and did a bunch of art commissions, creating character concepts for people online. Art has always been my passion, I love creating websites that are not only functional but also visually appealing.",
    section1_1: "But that's not all",
    section1_2: "—I'm also deeply passionate about continuous learning and growth. After getting hooked on marketing in university, I took extra courses and earned certificates from the University of Pennsylvania and the University of Virginia. This marketing background gives me an edge in web development by enhancing my skills in SEO, content creation, and understanding user behavior. It's all about combining creativity and strategy to build websites that are both beautiful and effective.",
    // section1_2: "—I'm also deeply passionate about ",
    // section1_3: "marketing, web design, and art",
    // section1_4: " These complementary skills allow me to approach projects from multiple perspectives and infuse creativity into everything I do.",
    section2_1: "In the showcase section,",
    section2_2: "you'll find a range of projects that demonstrate my skills in various areas. From dynamic web applications built with Next.js, MongoDB, Prisma, and Cloudinary to visually stunning designs that reflect my artistic background, my work is a testament to my commitment to excellence and innovation.",
    section3_1: "I believe that",
    section3_2: "blending these skills together creates a unique and valuable combination, enabling me to create innovative and holistic solutions for my clients and partners. I'm excited to share my journey with you and explore how my diverse background can add value to your projects.",
    end: "Thank you for visiting, and I look forward to connecting with you to discuss exciting possibilities and collaborations.",
};
